version: '3.8'

services:
  # 1. FastAPI Backend
  backend:
    build: ./backend
    container_name: fastapi_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app  # Změny v kódu se projeví hned (hot-reload)
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # 2. PostgreSQL Databáze
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Aby data nezmizela po vypnutí
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql # Automatické nahrání DB při prvním zapnutí
      - ./02_data.sql:/docker-entrypoint-initdb.d/02_data.sql # Automatické nahraní prvotních dat do DB
    env_file:
      - .env
    ports:
      - "5432:5432"

  # 3. Nástroj pro správu DB (DbGate)
  dbgate:
    image: dbgate/dbgate
    container_name: db_client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: